name: ci

on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup pnpm
        uses: pnpm/action-setup@v4

      - name: setup node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: pnpm

      - name: install deps
        run: pnpm install --prod

      - name: build
        run: pnpm build

      - name: deploy
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: dist/
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SCRIPT_AFTER_REQUIRED: true
          SCRIPT_AFTER: |
            pm2 restart asyomei.su
